server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cambus
    username: postgres
    password: 1234
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
